"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from deutschland.pflanzenschutzmittelzulassung.exceptions import ApiAttributeError
from deutschland.pflanzenschutzmittelzulassung.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    OpenApiModel,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


class InlineResponse2004Items(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {}

    validations = {}

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return (
            bool,
            date,
            datetime,
            dict,
            float,
            int,
            list,
            str,
            none_type,
        )  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            "antragnr": (str,),  # noqa: E501
            "anwendungen_anz_je_befall": (float,),  # noqa: E501
            "anwendungen_max_je_kultur": (float,),  # noqa: E501
            "anwendungen_max_je_vegetation": (float,),  # noqa: E501
            "anwendungsbereich": (str,),  # noqa: E501
            "anwendungstechnik": (str,),  # noqa: E501
            "awgnr": (str,),  # noqa: E501
            "awg_id": (str,),  # noqa: E501
            "aw_abstand_bis": (float,),  # noqa: E501
            "aw_abstand_einheit": (str,),  # noqa: E501
            "aw_abstand_von": (float,),  # noqa: E501
            "einsatzgebiet": (str,),  # noqa: E501
            "genehmigung": (str,),  # noqa: E501
            "huk": (str,),  # noqa: E501
            "kennr": (str,),  # noqa: E501
            "kultur_erl": (str,),  # noqa: E501
            "m_row": (str,),  # noqa: E501
            "schadorg_erl": (str,),  # noqa: E501
            "stadium_kultur_bem": (str,),  # noqa: E501
            "stadium_kultur_bis": (str,),  # noqa: E501
            "stadium_kultur_kodeliste": (float,),  # noqa: E501
            "stadium_kultur_von": (str,),  # noqa: E501
            "stadium_schadorg_bem": (str,),  # noqa: E501
            "stadium_schadorg_bis": (str,),  # noqa: E501
            "stadium_schadorg_kodeliste": (float,),  # noqa: E501
            "stadium_schadorg_von": (str,),  # noqa: E501
            "wirkungsbereich": (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None

    attribute_map = {
        "antragnr": "ANTRAGNR",  # noqa: E501
        "anwendungen_anz_je_befall": "ANWENDUNGEN_ANZ_JE_BEFALL",  # noqa: E501
        "anwendungen_max_je_kultur": "ANWENDUNGEN_MAX_JE_KULTUR",  # noqa: E501
        "anwendungen_max_je_vegetation": "ANWENDUNGEN_MAX_JE_VEGETATION",  # noqa: E501
        "anwendungsbereich": "ANWENDUNGSBEREICH",  # noqa: E501
        "anwendungstechnik": "ANWENDUNGSTECHNIK",  # noqa: E501
        "awgnr": "AWGNR",  # noqa: E501
        "awg_id": "AWG_ID",  # noqa: E501
        "aw_abstand_bis": "AW_ABSTAND_BIS",  # noqa: E501
        "aw_abstand_einheit": "AW_ABSTAND_EINHEIT",  # noqa: E501
        "aw_abstand_von": "AW_ABSTAND_VON",  # noqa: E501
        "einsatzgebiet": "EINSATZGEBIET",  # noqa: E501
        "genehmigung": "GENEHMIGUNG",  # noqa: E501
        "huk": "HUK",  # noqa: E501
        "kennr": "KENNR",  # noqa: E501
        "kultur_erl": "KULTUR_ERL",  # noqa: E501
        "m_row": "M_ROW$$",  # noqa: E501
        "schadorg_erl": "SCHADORG_ERL",  # noqa: E501
        "stadium_kultur_bem": "STADIUM_KULTUR_BEM",  # noqa: E501
        "stadium_kultur_bis": "STADIUM_KULTUR_BIS",  # noqa: E501
        "stadium_kultur_kodeliste": "STADIUM_KULTUR_KODELISTE",  # noqa: E501
        "stadium_kultur_von": "STADIUM_KULTUR_VON",  # noqa: E501
        "stadium_schadorg_bem": "STADIUM_SCHADORG_BEM",  # noqa: E501
        "stadium_schadorg_bis": "STADIUM_SCHADORG_BIS",  # noqa: E501
        "stadium_schadorg_kodeliste": "STADIUM_SCHADORG_KODELISTE",  # noqa: E501
        "stadium_schadorg_von": "STADIUM_SCHADORG_VON",  # noqa: E501
        "wirkungsbereich": "WIRKUNGSBEREICH",  # noqa: E501
    }

    read_only_vars = {}

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """InlineResponse2004Items - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            antragnr (str): [optional]  # noqa: E501
            anwendungen_anz_je_befall (float): [optional]  # noqa: E501
            anwendungen_max_je_kultur (float): [optional]  # noqa: E501
            anwendungen_max_je_vegetation (float): [optional]  # noqa: E501
            anwendungsbereich (str): [optional]  # noqa: E501
            anwendungstechnik (str): [optional]  # noqa: E501
            awgnr (str): [optional]  # noqa: E501
            awg_id (str): [optional]  # noqa: E501
            aw_abstand_bis (float): [optional]  # noqa: E501
            aw_abstand_einheit (str): [optional]  # noqa: E501
            aw_abstand_von (float): [optional]  # noqa: E501
            einsatzgebiet (str): [optional]  # noqa: E501
            genehmigung (str): [optional]  # noqa: E501
            huk (str): [optional]  # noqa: E501
            kennr (str): [optional]  # noqa: E501
            kultur_erl (str): [optional]  # noqa: E501
            m_row (str): [optional]  # noqa: E501
            schadorg_erl (str): [optional]  # noqa: E501
            stadium_kultur_bem (str): [optional]  # noqa: E501
            stadium_kultur_bis (str): [optional]  # noqa: E501
            stadium_kultur_kodeliste (float): [optional]  # noqa: E501
            stadium_kultur_von (str): [optional]  # noqa: E501
            stadium_schadorg_bem (str): [optional]  # noqa: E501
            stadium_schadorg_bis (str): [optional]  # noqa: E501
            stadium_schadorg_kodeliste (float): [optional]  # noqa: E501
            stadium_schadorg_von (str): [optional]  # noqa: E501
            wirkungsbereich (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop("_check_type", True)
        _spec_property_naming = kwargs.pop("_spec_property_naming", True)
        _path_to_item = kwargs.pop("_path_to_item", ())
        _configuration = kwargs.pop("_configuration", None)
        _visited_composed_classes = kwargs.pop("_visited_composed_classes", ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments."
                        % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if (
                var_name not in self.attribute_map
                and self._configuration is not None
                and self._configuration.discard_unknown_keys
                and self.additional_properties_type is None
            ):
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set(
        [
            "_data_store",
            "_check_type",
            "_spec_property_naming",
            "_path_to_item",
            "_configuration",
            "_visited_composed_classes",
        ]
    )

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """InlineResponse2004Items - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            antragnr (str): [optional]  # noqa: E501
            anwendungen_anz_je_befall (float): [optional]  # noqa: E501
            anwendungen_max_je_kultur (float): [optional]  # noqa: E501
            anwendungen_max_je_vegetation (float): [optional]  # noqa: E501
            anwendungsbereich (str): [optional]  # noqa: E501
            anwendungstechnik (str): [optional]  # noqa: E501
            awgnr (str): [optional]  # noqa: E501
            awg_id (str): [optional]  # noqa: E501
            aw_abstand_bis (float): [optional]  # noqa: E501
            aw_abstand_einheit (str): [optional]  # noqa: E501
            aw_abstand_von (float): [optional]  # noqa: E501
            einsatzgebiet (str): [optional]  # noqa: E501
            genehmigung (str): [optional]  # noqa: E501
            huk (str): [optional]  # noqa: E501
            kennr (str): [optional]  # noqa: E501
            kultur_erl (str): [optional]  # noqa: E501
            m_row (str): [optional]  # noqa: E501
            schadorg_erl (str): [optional]  # noqa: E501
            stadium_kultur_bem (str): [optional]  # noqa: E501
            stadium_kultur_bis (str): [optional]  # noqa: E501
            stadium_kultur_kodeliste (float): [optional]  # noqa: E501
            stadium_kultur_von (str): [optional]  # noqa: E501
            stadium_schadorg_bem (str): [optional]  # noqa: E501
            stadium_schadorg_bis (str): [optional]  # noqa: E501
            stadium_schadorg_kodeliste (float): [optional]  # noqa: E501
            stadium_schadorg_von (str): [optional]  # noqa: E501
            wirkungsbereich (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop("_check_type", True)
        _spec_property_naming = kwargs.pop("_spec_property_naming", False)
        _path_to_item = kwargs.pop("_path_to_item", ())
        _configuration = kwargs.pop("_configuration", None)
        _visited_composed_classes = kwargs.pop("_visited_composed_classes", ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments."
                        % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if (
                var_name not in self.attribute_map
                and self._configuration is not None
                and self._configuration.discard_unknown_keys
                and self.additional_properties_type is None
            ):
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(
                    f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                    f"class with read only attributes."
                )
