"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.date import DATE

from deutschland import pflanzenschutzmittelzulassung

globals()["DATE"] = DATE
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20034_items import (
    InlineResponse20034Items,
)


class TestInlineResponse20034Items(unittest.TestCase):
    """InlineResponse20034Items unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20034Items(self):
        """Test InlineResponse20034Items"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20034Items()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
