"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.kultur_gruppe_get200_response_items_inner import (
    KulturGruppeGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["KulturGruppeGet200ResponseItemsInner"] = KulturGruppeGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.kultur_gruppe_get200_response import (
    KulturGruppeGet200Response,
)


class TestKulturGruppeGet200Response(unittest.TestCase):
    """KulturGruppeGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKulturGruppeGet200Response(self):
        """Test KulturGruppeGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = KulturGruppeGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
