"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20022_items import (
    InlineResponse20022Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20022Items"] = InlineResponse20022Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20022 import (
    InlineResponse20022,
)


class TestInlineResponse20022(unittest.TestCase):
    """InlineResponse20022 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20022(self):
        """Test InlineResponse20022"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20022()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
