"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response200_items import (
    InlineResponse200Items,
)

from deutschland import pflanzenschutzmittelzulassung


class TestInlineResponse200Items(unittest.TestCase):
    """InlineResponse200Items unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200Items(self):
        """Test InlineResponse200Items"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse200Items()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
