"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20020_items import (
    InlineResponse20020Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20020Items"] = InlineResponse20020Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20020 import (
    InlineResponse20020,
)


class TestInlineResponse20020(unittest.TestCase):
    """InlineResponse20020 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20020(self):
        """Test InlineResponse20020"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20020()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
