"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20030_items import (
    InlineResponse20030Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20030Items"] = InlineResponse20030Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20030 import (
    InlineResponse20030,
)


class TestInlineResponse20030(unittest.TestCase):
    """InlineResponse20030 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20030(self):
        """Test InlineResponse20030"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20030()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
