"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.date import DATE

from deutschland import pflanzenschutzmittelzulassung

globals()["DATE"] = DATE
from deutschland.pflanzenschutzmittelzulassung.model.mittel_abgelaufen_get200_response_items_inner import (
    MittelAbgelaufenGet200ResponseItemsInner,
)


class TestMittelAbgelaufenGet200ResponseItemsInner(unittest.TestCase):
    """MittelAbgelaufenGet200ResponseItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMittelAbgelaufenGet200ResponseItemsInner(self):
        """Test MittelAbgelaufenGet200ResponseItemsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MittelAbgelaufenGet200ResponseItemsInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
