"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20037_items import (
    InlineResponse20037Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20037Items"] = InlineResponse20037Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20037 import (
    InlineResponse20037,
)


class TestInlineResponse20037(unittest.TestCase):
    """InlineResponse20037 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20037(self):
        """Test InlineResponse20037"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20037()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
