"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.auflage_redu_get200_response_items_inner import (
    AuflageReduGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["AuflageReduGet200ResponseItemsInner"] = AuflageReduGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.auflage_redu_get200_response import (
    AuflageReduGet200Response,
)


class TestAuflageReduGet200Response(unittest.TestCase):
    """AuflageReduGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuflageReduGet200Response(self):
        """Test AuflageReduGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuflageReduGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
