"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.pflanzenschutzmittelzulassung.api.default_api import (  # noqa: E501
    DefaultApi,
)

from deutschland import pflanzenschutzmittelzulassung


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_adresse_get(self):
        """Test case for adresse_get"""
        pass

    def test_antrag_get(self):
        """Test case for antrag_get"""
        pass

    def test_auflage_redu_get(self):
        """Test case for auflage_redu_get"""
        pass

    def test_auflagen_get(self):
        """Test case for auflagen_get"""
        pass

    def test_awg_aufwand_get(self):
        """Test case for awg_aufwand_get"""
        pass

    def test_awg_bem_get(self):
        """Test case for awg_bem_get"""
        pass

    def test_awg_get(self):
        """Test case for awg_get"""
        pass

    def test_awg_kultur_get(self):
        """Test case for awg_kultur_get"""
        pass

    def test_awg_partner_aufwand_get(self):
        """Test case for awg_partner_aufwand_get"""
        pass

    def test_awg_partner_get(self):
        """Test case for awg_partner_get"""
        pass

    def test_awg_schadorg_get(self):
        """Test case for awg_schadorg_get"""
        pass

    def test_awg_verwendungszweck_get(self):
        """Test case for awg_verwendungszweck_get"""
        pass

    def test_awg_wartezeit_ausg_kultur_get(self):
        """Test case for awg_wartezeit_ausg_kultur_get"""
        pass

    def test_awg_wartezeit_get(self):
        """Test case for awg_wartezeit_get"""
        pass

    def test_awg_zeitpunkt_get(self):
        """Test case for awg_zeitpunkt_get"""
        pass

    def test_awg_zulassung_get(self):
        """Test case for awg_zulassung_get"""
        pass

    def test_ghs_gefahrenhinweise_get(self):
        """Test case for ghs_gefahrenhinweise_get"""
        pass

    def test_ghs_gefahrensymbole_get(self):
        """Test case for ghs_gefahrensymbole_get"""
        pass

    def test_ghs_sicherheitshinweise_get(self):
        """Test case for ghs_sicherheitshinweise_get"""
        pass

    def test_ghs_signalwoerter_get(self):
        """Test case for ghs_signalwoerter_get"""
        pass

    def test_hinweis_get(self):
        """Test case for hinweis_get"""
        pass

    def test_kode_get(self):
        """Test case for kode_get"""
        pass

    def test_kodeliste_feldname_get(self):
        """Test case for kodeliste_feldname_get"""
        pass

    def test_kodeliste_get(self):
        """Test case for kodeliste_get"""
        pass

    def test_kultur_gruppe_get(self):
        """Test case for kultur_gruppe_get"""
        pass

    def test_mittel_abgelaufen_get(self):
        """Test case for mittel_abgelaufen_get"""
        pass

    def test_mittel_abpackung_get(self):
        """Test case for mittel_abpackung_get"""
        pass

    def test_mittel_gefahren_symbol_get(self):
        """Test case for mittel_gefahren_symbol_get"""
        pass

    def test_mittel_get(self):
        """Test case for mittel_get"""
        pass

    def test_mittel_vertrieb_get(self):
        """Test case for mittel_vertrieb_get"""
        pass

    def test_mittel_wirkbereich_get(self):
        """Test case for mittel_wirkbereich_get"""
        pass

    def test_parallelimport_abgelaufen_get(self):
        """Test case for parallelimport_abgelaufen_get"""
        pass

    def test_parallelimport_gueltig_get(self):
        """Test case for parallelimport_gueltig_get"""
        pass

    def test_schadorg_gruppe_get(self):
        """Test case for schadorg_gruppe_get"""
        pass

    def test_staerkung_get(self):
        """Test case for staerkung_get"""
        pass

    def test_staerkung_vertrieb_get(self):
        """Test case for staerkung_vertrieb_get"""
        pass

    def test_stand_get(self):
        """Test case for stand_get"""
        pass

    def test_wirkstoff_gehalt_get(self):
        """Test case for wirkstoff_gehalt_get"""
        pass

    def test_wirkstoff_get(self):
        """Test case for wirkstoff_get"""
        pass

    def test_zusatzstoff_get(self):
        """Test case for zusatzstoff_get"""
        pass

    def test_zusatzstoff_vertrieb_get(self):
        """Test case for zusatzstoff_vertrieb_get"""
        pass


if __name__ == "__main__":
    unittest.main()
