"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20013_items import (
    InlineResponse20013Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20013Items"] = InlineResponse20013Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20013 import (
    InlineResponse20013,
)


class TestInlineResponse20013(unittest.TestCase):
    """InlineResponse20013 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20013(self):
        """Test InlineResponse20013"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20013()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
