"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20024_items import (
    InlineResponse20024Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20024Items"] = InlineResponse20024Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20024 import (
    InlineResponse20024,
)


class TestInlineResponse20024(unittest.TestCase):
    """InlineResponse20024 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20024(self):
        """Test InlineResponse20024"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20024()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
