"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response2003_items import (
    InlineResponse2003Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse2003Items"] = InlineResponse2003Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response2003 import (
    InlineResponse2003,
)


class TestInlineResponse2003(unittest.TestCase):
    """InlineResponse2003 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003(self):
        """Test InlineResponse2003"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
