"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.auflagen_get200_response_items_inner import (
    AuflagenGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["AuflagenGet200ResponseItemsInner"] = AuflagenGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.auflagen_get200_response import (
    AuflagenGet200Response,
)


class TestAuflagenGet200Response(unittest.TestCase):
    """AuflagenGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuflagenGet200Response(self):
        """Test AuflagenGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuflagenGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
