"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20038_items import (
    InlineResponse20038Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20038Items"] = InlineResponse20038Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20038 import (
    InlineResponse20038,
)


class TestInlineResponse20038(unittest.TestCase):
    """InlineResponse20038 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20038(self):
        """Test InlineResponse20038"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20038()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
