"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.hinweis_get200_response_items_inner import (
    HinweisGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["HinweisGet200ResponseItemsInner"] = HinweisGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.hinweis_get200_response import (
    HinweisGet200Response,
)


class TestHinweisGet200Response(unittest.TestCase):
    """HinweisGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHinweisGet200Response(self):
        """Test HinweisGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HinweisGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
