"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.kode_get200_response_items_inner import (
    KodeGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["KodeGet200ResponseItemsInner"] = KodeGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.kode_get200_response import (
    KodeGet200Response,
)


class TestKodeGet200Response(unittest.TestCase):
    """KodeGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKodeGet200Response(self):
        """Test KodeGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = KodeGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
