"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.awg_bem_get200_response_items_inner import (
    AwgBemGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["AwgBemGet200ResponseItemsInner"] = AwgBemGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.awg_bem_get200_response import (
    AwgBemGet200Response,
)


class TestAwgBemGet200Response(unittest.TestCase):
    """AwgBemGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAwgBemGet200Response(self):
        """Test AwgBemGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AwgBemGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
