"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20023_items import (
    InlineResponse20023Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20023Items"] = InlineResponse20023Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20023 import (
    InlineResponse20023,
)


class TestInlineResponse20023(unittest.TestCase):
    """InlineResponse20023 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20023(self):
        """Test InlineResponse20023"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20023()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
