"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.date import DATE

from deutschland import pflanzenschutzmittelzulassung

globals()["DATE"] = DATE
from deutschland.pflanzenschutzmittelzulassung.model.mittel_get200_response_items_inner import (
    MittelGet200ResponseItemsInner,
)


class TestMittelGet200ResponseItemsInner(unittest.TestCase):
    """MittelGet200ResponseItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMittelGet200ResponseItemsInner(self):
        """Test MittelGet200ResponseItemsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MittelGet200ResponseItemsInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
