"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20028_items import (
    InlineResponse20028Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20028Items"] = InlineResponse20028Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20028 import (
    InlineResponse20028,
)


class TestInlineResponse20028(unittest.TestCase):
    """InlineResponse20028 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20028(self):
        """Test InlineResponse20028"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20028()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
