"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.parallelimport_abgelaufen_get200_response_items_inner import (
    ParallelimportAbgelaufenGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()[
    "ParallelimportAbgelaufenGet200ResponseItemsInner"
] = ParallelimportAbgelaufenGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.parallelimport_abgelaufen_get200_response import (
    ParallelimportAbgelaufenGet200Response,
)


class TestParallelimportAbgelaufenGet200Response(unittest.TestCase):
    """ParallelimportAbgelaufenGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParallelimportAbgelaufenGet200Response(self):
        """Test ParallelimportAbgelaufenGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParallelimportAbgelaufenGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
