"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.kodeliste_feldname_get200_response_items_inner import (
    KodelisteFeldnameGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()[
    "KodelisteFeldnameGet200ResponseItemsInner"
] = KodelisteFeldnameGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.kodeliste_feldname_get200_response import (
    KodelisteFeldnameGet200Response,
)


class TestKodelisteFeldnameGet200Response(unittest.TestCase):
    """KodelisteFeldnameGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKodelisteFeldnameGet200Response(self):
        """Test KodelisteFeldnameGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = KodelisteFeldnameGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
