"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response2006_items import (
    InlineResponse2006Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse2006Items"] = InlineResponse2006Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response2006 import (
    InlineResponse2006,
)


class TestInlineResponse2006(unittest.TestCase):
    """InlineResponse2006 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2006(self):
        """Test InlineResponse2006"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2006()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
