"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.kodeliste_get200_response_items_inner import (
    KodelisteGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["KodelisteGet200ResponseItemsInner"] = KodelisteGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.kodeliste_get200_response import (
    KodelisteGet200Response,
)


class TestKodelisteGet200Response(unittest.TestCase):
    """KodelisteGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKodelisteGet200Response(self):
        """Test KodelisteGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = KodelisteGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
