"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20014_items import (
    InlineResponse20014Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20014Items"] = InlineResponse20014Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20014 import (
    InlineResponse20014,
)


class TestInlineResponse20014(unittest.TestCase):
    """InlineResponse20014 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20014(self):
        """Test InlineResponse20014"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20014()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
