"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20032_items import (
    InlineResponse20032Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20032Items"] = InlineResponse20032Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20032 import (
    InlineResponse20032,
)


class TestInlineResponse20032(unittest.TestCase):
    """InlineResponse20032 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20032(self):
        """Test InlineResponse20032"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20032()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
