"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.ghs_gefahrenhinweise_get200_response_items_inner import (
    GhsGefahrenhinweiseGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()[
    "GhsGefahrenhinweiseGet200ResponseItemsInner"
] = GhsGefahrenhinweiseGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.ghs_gefahrenhinweise_get200_response import (
    GhsGefahrenhinweiseGet200Response,
)


class TestGhsGefahrenhinweiseGet200Response(unittest.TestCase):
    """GhsGefahrenhinweiseGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGhsGefahrenhinweiseGet200Response(self):
        """Test GhsGefahrenhinweiseGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GhsGefahrenhinweiseGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
