"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response2009_items import (
    InlineResponse2009Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse2009Items"] = InlineResponse2009Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response2009 import (
    InlineResponse2009,
)


class TestInlineResponse2009(unittest.TestCase):
    """InlineResponse2009 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2009(self):
        """Test InlineResponse2009"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2009()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
