"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20011_items import (
    InlineResponse20011Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20011Items"] = InlineResponse20011Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20011 import (
    InlineResponse20011,
)


class TestInlineResponse20011(unittest.TestCase):
    """InlineResponse20011 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20011(self):
        """Test InlineResponse20011"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20011()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
