"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.adresse_get200_response_items_inner import (
    AdresseGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["AdresseGet200ResponseItemsInner"] = AdresseGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.adresse_get200_response import (
    AdresseGet200Response,
)


class TestAdresseGet200Response(unittest.TestCase):
    """AdresseGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdresseGet200Response(self):
        """Test AdresseGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AdresseGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
