"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.mittel_abpackung_get200_response_items_inner import (
    MittelAbpackungGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()[
    "MittelAbpackungGet200ResponseItemsInner"
] = MittelAbpackungGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.mittel_abpackung_get200_response import (
    MittelAbpackungGet200Response,
)


class TestMittelAbpackungGet200Response(unittest.TestCase):
    """MittelAbpackungGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMittelAbpackungGet200Response(self):
        """Test MittelAbpackungGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MittelAbpackungGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
