"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.ghs_signalwoerter_get200_response_items_inner import (
    GhsSignalwoerterGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()[
    "GhsSignalwoerterGet200ResponseItemsInner"
] = GhsSignalwoerterGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.ghs_signalwoerter_get200_response import (
    GhsSignalwoerterGet200Response,
)


class TestGhsSignalwoerterGet200Response(unittest.TestCase):
    """GhsSignalwoerterGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGhsSignalwoerterGet200Response(self):
        """Test GhsSignalwoerterGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GhsSignalwoerterGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
