"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20021_items import (
    InlineResponse20021Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20021Items"] = InlineResponse20021Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20021 import (
    InlineResponse20021,
)


class TestInlineResponse20021(unittest.TestCase):
    """InlineResponse20021 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20021(self):
        """Test InlineResponse20021"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20021()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
