"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20034_items import (
    InlineResponse20034Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20034Items"] = InlineResponse20034Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20034 import (
    InlineResponse20034,
)


class TestInlineResponse20034(unittest.TestCase):
    """InlineResponse20034 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20034(self):
        """Test InlineResponse20034"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20034()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
