"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.mittel_abgelaufen_get200_response_items_inner import (
    MittelAbgelaufenGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()[
    "MittelAbgelaufenGet200ResponseItemsInner"
] = MittelAbgelaufenGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.mittel_abgelaufen_get200_response import (
    MittelAbgelaufenGet200Response,
)


class TestMittelAbgelaufenGet200Response(unittest.TestCase):
    """MittelAbgelaufenGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMittelAbgelaufenGet200Response(self):
        """Test MittelAbgelaufenGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MittelAbgelaufenGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
