"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20031_items import (
    InlineResponse20031Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20031Items"] = InlineResponse20031Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20031 import (
    InlineResponse20031,
)


class TestInlineResponse20031(unittest.TestCase):
    """InlineResponse20031 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20031(self):
        """Test InlineResponse20031"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20031()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
