"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response2001_items import (
    InlineResponse2001Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse2001Items"] = InlineResponse2001Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response2001 import (
    InlineResponse2001,
)


class TestInlineResponse2001(unittest.TestCase):
    """InlineResponse2001 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001(self):
        """Test InlineResponse2001"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2001()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
