"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.awg_get200_response_items_inner import (
    AwgGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung


class TestAwgGet200ResponseItemsInner(unittest.TestCase):
    """AwgGet200ResponseItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAwgGet200ResponseItemsInner(self):
        """Test AwgGet200ResponseItemsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AwgGet200ResponseItemsInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
