"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.awg_zeitpunkt_get200_response_items_inner import (
    AwgZeitpunktGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["AwgZeitpunktGet200ResponseItemsInner"] = AwgZeitpunktGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.awg_zeitpunkt_get200_response import (
    AwgZeitpunktGet200Response,
)


class TestAwgZeitpunktGet200Response(unittest.TestCase):
    """AwgZeitpunktGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAwgZeitpunktGet200Response(self):
        """Test AwgZeitpunktGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AwgZeitpunktGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
