"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.date import DATE

from deutschland import pflanzenschutzmittelzulassung

globals()["DATE"] = DATE
from deutschland.pflanzenschutzmittelzulassung.model.stand_get200_response_items_inner import (
    StandGet200ResponseItemsInner,
)


class TestStandGet200ResponseItemsInner(unittest.TestCase):
    """StandGet200ResponseItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStandGet200ResponseItemsInner(self):
        """Test StandGet200ResponseItemsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StandGet200ResponseItemsInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
