"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.mittel_vertrieb_get200_response_items_inner import (
    MittelVertriebGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()[
    "MittelVertriebGet200ResponseItemsInner"
] = MittelVertriebGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.mittel_vertrieb_get200_response import (
    MittelVertriebGet200Response,
)


class TestMittelVertriebGet200Response(unittest.TestCase):
    """MittelVertriebGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMittelVertriebGet200Response(self):
        """Test MittelVertriebGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MittelVertriebGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
