"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20033_items import (
    InlineResponse20033Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20033Items"] = InlineResponse20033Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20033 import (
    InlineResponse20033,
)


class TestInlineResponse20033(unittest.TestCase):
    """InlineResponse20033 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20033(self):
        """Test InlineResponse20033"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20033()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
