"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20018_items import (
    InlineResponse20018Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20018Items"] = InlineResponse20018Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20018 import (
    InlineResponse20018,
)


class TestInlineResponse20018(unittest.TestCase):
    """InlineResponse20018 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20018(self):
        """Test InlineResponse20018"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20018()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
