"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.awg_partner_get200_response_items_inner import (
    AwgPartnerGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["AwgPartnerGet200ResponseItemsInner"] = AwgPartnerGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.awg_partner_get200_response import (
    AwgPartnerGet200Response,
)


class TestAwgPartnerGet200Response(unittest.TestCase):
    """AwgPartnerGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAwgPartnerGet200Response(self):
        """Test AwgPartnerGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AwgPartnerGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
