"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20026_items import (
    InlineResponse20026Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20026Items"] = InlineResponse20026Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20026 import (
    InlineResponse20026,
)


class TestInlineResponse20026(unittest.TestCase):
    """InlineResponse20026 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20026(self):
        """Test InlineResponse20026"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20026()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
