"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response2005_items import (
    InlineResponse2005Items,
)

from deutschland import pflanzenschutzmittelzulassung


class TestInlineResponse2005Items(unittest.TestCase):
    """InlineResponse2005Items unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2005Items(self):
        """Test InlineResponse2005Items"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2005Items()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
