"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.awg_wartezeit_get200_response_items_inner import (
    AwgWartezeitGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["AwgWartezeitGet200ResponseItemsInner"] = AwgWartezeitGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.awg_wartezeit_get200_response import (
    AwgWartezeitGet200Response,
)


class TestAwgWartezeitGet200Response(unittest.TestCase):
    """AwgWartezeitGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAwgWartezeitGet200Response(self):
        """Test AwgWartezeitGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AwgWartezeitGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
