"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.mittel_wirkbereich_get200_response_items_inner import (
    MittelWirkbereichGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()[
    "MittelWirkbereichGet200ResponseItemsInner"
] = MittelWirkbereichGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.mittel_wirkbereich_get200_response import (
    MittelWirkbereichGet200Response,
)


class TestMittelWirkbereichGet200Response(unittest.TestCase):
    """MittelWirkbereichGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMittelWirkbereichGet200Response(self):
        """Test MittelWirkbereichGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MittelWirkbereichGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
