"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.wirkstoff_gehalt_get200_response_items_inner import (
    WirkstoffGehaltGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung


class TestWirkstoffGehaltGet200ResponseItemsInner(unittest.TestCase):
    """WirkstoffGehaltGet200ResponseItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWirkstoffGehaltGet200ResponseItemsInner(self):
        """Test WirkstoffGehaltGet200ResponseItemsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WirkstoffGehaltGet200ResponseItemsInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
