"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.staerkung_get200_response_items_inner import (
    StaerkungGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["StaerkungGet200ResponseItemsInner"] = StaerkungGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.staerkung_get200_response import (
    StaerkungGet200Response,
)


class TestStaerkungGet200Response(unittest.TestCase):
    """StaerkungGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStaerkungGet200Response(self):
        """Test StaerkungGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StaerkungGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
