"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.mittel_get200_response_items_inner import (
    MittelGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["MittelGet200ResponseItemsInner"] = MittelGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.mittel_get200_response import (
    MittelGet200Response,
)


class TestMittelGet200Response(unittest.TestCase):
    """MittelGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMittelGet200Response(self):
        """Test MittelGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MittelGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
