"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response2008_items import (
    InlineResponse2008Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse2008Items"] = InlineResponse2008Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response2008 import (
    InlineResponse2008,
)


class TestInlineResponse2008(unittest.TestCase):
    """InlineResponse2008 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2008(self):
        """Test InlineResponse2008"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2008()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
