"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20025_items import (
    InlineResponse20025Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20025Items"] = InlineResponse20025Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20025 import (
    InlineResponse20025,
)


class TestInlineResponse20025(unittest.TestCase):
    """InlineResponse20025 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20025(self):
        """Test InlineResponse20025"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20025()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
