"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.awg_zulassung_get200_response_items_inner import (
    AwgZulassungGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["AwgZulassungGet200ResponseItemsInner"] = AwgZulassungGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.awg_zulassung_get200_response import (
    AwgZulassungGet200Response,
)


class TestAwgZulassungGet200Response(unittest.TestCase):
    """AwgZulassungGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAwgZulassungGet200Response(self):
        """Test AwgZulassungGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AwgZulassungGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
