"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.zusatzstoff_get200_response_items_inner import (
    ZusatzstoffGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["ZusatzstoffGet200ResponseItemsInner"] = ZusatzstoffGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.zusatzstoff_get200_response import (
    ZusatzstoffGet200Response,
)


class TestZusatzstoffGet200Response(unittest.TestCase):
    """ZusatzstoffGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testZusatzstoffGet200Response(self):
        """Test ZusatzstoffGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ZusatzstoffGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
