"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response2005_items import (
    InlineResponse2005Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse2005Items"] = InlineResponse2005Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response2005 import (
    InlineResponse2005,
)


class TestInlineResponse2005(unittest.TestCase):
    """InlineResponse2005 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2005(self):
        """Test InlineResponse2005"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2005()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
