"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.date import DATE

from deutschland import pflanzenschutzmittelzulassung

globals()["DATE"] = DATE
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20015_items import (
    InlineResponse20015Items,
)


class TestInlineResponse20015Items(unittest.TestCase):
    """InlineResponse20015Items unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20015Items(self):
        """Test InlineResponse20015Items"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20015Items()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
