"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20010_items import (
    InlineResponse20010Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20010Items"] = InlineResponse20010Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20010 import (
    InlineResponse20010,
)


class TestInlineResponse20010(unittest.TestCase):
    """InlineResponse20010 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20010(self):
        """Test InlineResponse20010"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20010()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
