"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.awg_partner_aufwand_get200_response_items_inner import (
    AwgPartnerAufwandGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()[
    "AwgPartnerAufwandGet200ResponseItemsInner"
] = AwgPartnerAufwandGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.awg_partner_aufwand_get200_response import (
    AwgPartnerAufwandGet200Response,
)


class TestAwgPartnerAufwandGet200Response(unittest.TestCase):
    """AwgPartnerAufwandGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAwgPartnerAufwandGet200Response(self):
        """Test AwgPartnerAufwandGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AwgPartnerAufwandGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
