"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.mittel_gefahren_symbol_get200_response_items_inner import (
    MittelGefahrenSymbolGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()[
    "MittelGefahrenSymbolGet200ResponseItemsInner"
] = MittelGefahrenSymbolGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.mittel_gefahren_symbol_get200_response import (
    MittelGefahrenSymbolGet200Response,
)


class TestMittelGefahrenSymbolGet200Response(unittest.TestCase):
    """MittelGefahrenSymbolGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMittelGefahrenSymbolGet200Response(self):
        """Test MittelGefahrenSymbolGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MittelGefahrenSymbolGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
