"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20019_items import (
    InlineResponse20019Items,
)

from deutschland import pflanzenschutzmittelzulassung


class TestInlineResponse20019Items(unittest.TestCase):
    """InlineResponse20019Items unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20019Items(self):
        """Test InlineResponse20019Items"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20019Items()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
