"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.ghs_sicherheitshinweise_get200_response_items_inner import (
    GhsSicherheitshinweiseGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()[
    "GhsSicherheitshinweiseGet200ResponseItemsInner"
] = GhsSicherheitshinweiseGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.ghs_sicherheitshinweise_get200_response import (
    GhsSicherheitshinweiseGet200Response,
)


class TestGhsSicherheitshinweiseGet200Response(unittest.TestCase):
    """GhsSicherheitshinweiseGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGhsSicherheitshinweiseGet200Response(self):
        """Test GhsSicherheitshinweiseGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GhsSicherheitshinweiseGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
