"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20035_items import (
    InlineResponse20035Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20035Items"] = InlineResponse20035Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20035 import (
    InlineResponse20035,
)


class TestInlineResponse20035(unittest.TestCase):
    """InlineResponse20035 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20035(self):
        """Test InlineResponse20035"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20035()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
