"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.ghs_gefahrensymbole_get200_response_items_inner import (
    GhsGefahrensymboleGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung

globals()[
    "GhsGefahrensymboleGet200ResponseItemsInner"
] = GhsGefahrensymboleGet200ResponseItemsInner
from deutschland.pflanzenschutzmittelzulassung.model.ghs_gefahrensymbole_get200_response import (
    GhsGefahrensymboleGet200Response,
)


class TestGhsGefahrensymboleGet200Response(unittest.TestCase):
    """GhsGefahrensymboleGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGhsGefahrensymboleGet200Response(self):
        """Test GhsGefahrensymboleGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GhsGefahrensymboleGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
