"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20036_items import (
    InlineResponse20036Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20036Items"] = InlineResponse20036Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20036 import (
    InlineResponse20036,
)


class TestInlineResponse20036(unittest.TestCase):
    """InlineResponse20036 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20036(self):
        """Test InlineResponse20036"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20036()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
