"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.inline_response20039_items import (
    InlineResponse20039Items,
)

from deutschland import pflanzenschutzmittelzulassung

globals()["InlineResponse20039Items"] = InlineResponse20039Items
from deutschland.pflanzenschutzmittelzulassung.model.inline_response20039 import (
    InlineResponse20039,
)


class TestInlineResponse20039(unittest.TestCase):
    """InlineResponse20039 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20039(self):
        """Test InlineResponse20039"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20039()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
