"""
    ORDS generated API for api-v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.pflanzenschutzmittelzulassung.model.awg_kultur_get200_response_items_inner import (
    AwgKulturGet200ResponseItemsInner,
)

from deutschland import pflanzenschutzmittelzulassung


class TestAwgKulturGet200ResponseItemsInner(unittest.TestCase):
    """AwgKulturGet200ResponseItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAwgKulturGet200ResponseItemsInner(self):
        """Test AwgKulturGet200ResponseItemsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AwgKulturGet200ResponseItemsInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
